name: "Autodelivery"
description: "Deliver stuff from a single repository to multiple destinations."
author: "Danilo Pianini"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token. Must be a user token, GH Actions tokens won't work"
  GITHUB_USER:
    description: "GitHub username of the user performing the delivery. Defaults to GITHUB_ACTOR"
  CONFIGURATION_FILE:
    description: "Path to the Autodelivery YAML configuration file in the local repository"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'fast-forward'
  color: 'red'
