name: "Autodelivery"
description: "Deliver stuff from a single repository to multiple destinations."
author: "Danilo Pianini"
inputs:
  token:
    description: "Github secret token. Must be a user token, GH Actions tokens won't work"
    required: true
  user:
    description: "GitHub username of the user performing the delivery. Defaults internally to GITHUB_ACTOR"
    required: false
  configuration_file:
    description: "Path to the Autodelivery YAML configuration file in the local repository. Defaults to 'auto-delivery.yml'"
    required: false
    default: auto-delivery.yml
  commit_author:
    description: "Name of the committer"
    required: false
    default: "Autodelivery [bot]"
  author_email:
    description: "email of the committer"
    required: false
    default: 'autodelivery@autodelivery.bot'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.user }}
    - ${{ inputs.configuration_file }}
    - ${{ inputs.commit_author }}
    - ${{ inputs.author_email }}
branding:
  icon: 'fast-forward'
  color: 'red'
